version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: retail_system
    ports:
      - "3306:3306"
    networks:
      - spring-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p123456"]
      interval: 10s
      timeout: 5s
      retries: 5

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-container
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=retail_system
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - spring-network
    command: >
      sh -c "java -Dspring.datasource.url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false
                -Dspring.datasource.username=${MYSQL_USER}
                -Dspring.datasource.password=${MYSQL_PASSWORD}
                -Dspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
                -jar retail_system.jar"

networks:
  spring-network:
    driver: bridge
